export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Brand } from "./Brand";
export { default as About } from "./About";
export { default as Services } from "./Services";
export { default as Testimonial } from "./Testimonial";
export { default as Faq } from "./Faq";
export { default as Footer } from "./Footer";
export { default as Plans } from "./Plans";
